---
  
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  vars:

  # awx_prompted_fs: /boot

  tasks:

  - name: extend_fs | get fs mount
    shell: /bin/mount | grep "{{ awx_prompted_fs }} "
    #/dev/mapper/rootvg-var on /var type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
    register: fs_mount

  - name: extend_fs | get fs device
    debug:
      msg: "fs device name is: {{ fs_mount.stdout.split()[0] }}"
    register: awx_prompted_fs_device

  - name: extend_fs | get fs type
    debug:
      msg: "fs type is: {{ fs_mount.stdout.split()[4] }}"
    register: awx_prompted_fs_type

  - name: extend_fs | grow filesystem
    lvol:
      lv: "{{ awx_prompted_fs }}"
      size: "{{ awx_prompted_size }}"
      shrink: no
      resizefs: yes