---

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  #  vars:
  #  ansible_network_os: RedHat

  tasks:

  - name: passwd unexpire | Add +180 days
    debug:
      msg: "{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 180 )  ) }}"
    register: calculated_expiry_date

  - debug:
      msg: "{{ ansible_date_time.epoch | int + ( 86400 * 180 ) }}"


  - name: passwd unexpire | select user
    user:
      name: "{{ awx_prompted_user }}"
      expires: "{{ ansible_date_time.epoch | int + ( 86400 * 180 ) }}"

      # - debug: msg: "{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 180 )  ) }}"
      # ansible_date_time.epoch
      # +180 days is 1540015733 sec

# chage -l user1
# passwd --expire user1
# chage -l user1

# Last password change          : Oct 20, 2018
# Password expires          : never
# Password inactive         : never
# Account expires           : never
# Minimum number of days between password change    : 0
# Maximum number of days between password change    : 99999
# Number of days of warning before password expires : 7
